version: 2

sources:
  - name: stripe
    database: raw
    loaded_at_field: created
    loader: WHO

    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
      
    tables:
      - name: payment

models:
  - name: dim_customers
    description: One record per customer
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
      - name: lifetime_value
        tests:
          - not_null
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
  - name: stg_stripe_payments
    columns:
       - name: id
         tests:
           - not_null
           - unique
       - name: order_id
         tests:
           - not_null
           - relationships:
              to: ref('stg_orders')
              field: order_id
  - name: fct_orders
    description: "{{ doc('fct_orders') }}"
    columns:
      - name: id
        tests:
          - not_null
          - unique
